### ISSUE TITLE
Error when calling controller/extension/shipping/sameday/deleteAwb

### ISSUE THREAD

**Issue by robertiulianstoica** [sameday-courier/opencart-plugin#26]
When calling this endpoint for a specific order i am redirecter to the order info page because the exception catch is not handled.
However if i remove the exception catch iam receiving this error from the SDK:

Fatal error: Uncaught Sameday\Exceptions\SamedayOtherException in /home/impotri1/public_html/system/library/sameday-php-sdk/src/Sameday/SamedayClient.php:172 Stack trace: #0 /home/impotri1/public_html/system/library/sameday-php-sdk/src/Sameday/Sameday.php(146): Sameday\SamedayClient->sendRequest(Object(Sameday\Http\SamedayRequest)) #1 /home/impotri1/public_html/admin/controller/extension/shipping/sameday.php(1215): Sameday\Sameday->deleteAwb(Object(Sameday\Requests\SamedayDeleteAwbRequest)) #2 /home/impotri1/public_html/storage/modification/system/engine/action.php(79): ControllerExtensionShippingSameday->deleteAwb() #3 /home/impotri1/public_html/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #4 /home/impotri1/public_html/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index() #5 /home/impotri1/public_html/storage/modification/system/engine/router.php(114): Action->execute(Object(Registry)) #6 /home/impotri1/public_html/storage/modification/system/engine/route in /home/impotri1/public_html/system/library/sameday-php-sdk/src/Sameday/SamedayClient.php on line 172

Awb number i've tried to delete: 1ONBLN122377196

**Comment by Soptareanu** [comment]
> 1ONBLN122377196

Comanda de trasnport a fost deja preluata de catre curier, prin urmare awb-ul nu mai poate fi sters.

**Comment by robertiulianstoica** [comment]
Multumesc pentru raspuns, still, eroarea ar trebui sa fie returnata user-ului.

**Comment by Soptareanu** [comment]
> Multumesc pentru raspuns, still, eroarea ar trebui sa fie returnata user-ului.

Multumim pentru sugestie. Ne ocupam !
